### ISSUE TITLE
Support .NET 4.5

### ISSUE THREAD

**Issue by HalidCisse** [benaadams/Ben.Demystifier#15]
The nugget package target .NET4.6 which mean we can't use it on our .NET4.5 projects.
Thanks you for the greatness !!

**Comment by tobyhei** [comment]
Not sure if I should create a separate issue for this, but I'd love to see support for earlier versions of .net standard if possible (anything pre 2.0 would work for me personally)

Edit: My bad, it seems it's not possible to support this in .net standard < 2.0 because it uses StackTrace which was added in 2.0. https://github.com/dotnet/corefx/issues/12260

**Comment by dennisdoomen** [comment]
Didn't even notice that. Why is it targeting .NET 4.6 in the first place. It should target the lowest .NET Standard possible.

**Comment by benaadams** [comment]
Version 0.0.4 is on NuGet https://www.nuget.org/packages/Ben.Demystifier/0.0.4
